# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.create_sandbox_api import CreateSandboxApi


class TestCreateSandboxApi(unittest.TestCase):
    """ CreateSandboxApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.create_sandbox_api.CreateSandboxApi()

    def tearDown(self):
        pass

    def test_create_sandbox(self):
        """
        Test case for create_sandbox

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
