# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApplicationHostInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, host_name=None, host_uri=None):
        """
        ApplicationHostInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'host_name': 'str',
            'host_uri': 'str'
        }

        self.attribute_map = {
            'host_name': 'hostName',
            'host_uri': 'hostUri'
        }

        self._host_name = host_name
        self._host_uri = host_uri

    @property
    def host_name(self):
        """
        Gets the host_name of this ApplicationHostInfo.

        :return: The host_name of this ApplicationHostInfo.
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name):
        """
        Sets the host_name of this ApplicationHostInfo.

        :param host_name: The host_name of this ApplicationHostInfo.
        :type: str
        """

        self._host_name = host_name

    @property
    def host_uri(self):
        """
        Gets the host_uri of this ApplicationHostInfo.

        :return: The host_uri of this ApplicationHostInfo.
        :rtype: str
        """
        return self._host_uri

    @host_uri.setter
    def host_uri(self, host_uri):
        """
        Sets the host_uri of this ApplicationHostInfo.

        :param host_uri: The host_uri of this ApplicationHostInfo.
        :type: str
        """

        self._host_uri = host_uri

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApplicationHostInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
