# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApplianceDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, fqdn=None, host_name=None, ip=None):
        """
        ApplianceDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'fqdn': 'str',
            'host_name': 'str',
            'ip': 'str'
        }

        self.attribute_map = {
            'fqdn': 'fqdn',
            'host_name': 'hostName',
            'ip': 'ip'
        }

        self._fqdn = fqdn
        self._host_name = host_name
        self._ip = ip

    @property
    def fqdn(self):
        """
        Gets the fqdn of this ApplianceDetails.
        Fully Qualified Domain Name of an appliance

        :return: The fqdn of this ApplianceDetails.
        :rtype: str
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn):
        """
        Sets the fqdn of this ApplianceDetails.
        Fully Qualified Domain Name of an appliance

        :param fqdn: The fqdn of this ApplianceDetails.
        :type: str
        """

        self._fqdn = fqdn

    @property
    def host_name(self):
        """
        Gets the host_name of this ApplianceDetails.
        Hostname of an Appliance

        :return: The host_name of this ApplianceDetails.
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name):
        """
        Sets the host_name of this ApplianceDetails.
        Hostname of an Appliance

        :param host_name: The host_name of this ApplianceDetails.
        :type: str
        """

        self._host_name = host_name

    @property
    def ip(self):
        """
        Gets the ip of this ApplianceDetails.
        IP Address of an appliance

        :return: The ip of this ApplianceDetails.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """
        Sets the ip of this ApplianceDetails.
        IP Address of an appliance

        :param ip: The ip of this ApplianceDetails.
        :type: str
        """

        self._ip = ip

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApplianceDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
