# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OracleConfig(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, database_name=None, memory_target_in_mb=None, oracle_home_path=None, runtime_path=None):
        """
        OracleConfig - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'database_name': 'str',
            'memory_target_in_mb': 'int',
            'oracle_home_path': 'str',
            'runtime_path': 'str'
        }

        self.attribute_map = {
            'database_name': 'databaseName',
            'memory_target_in_mb': 'memoryTargetInMB',
            'oracle_home_path': 'oracleHomePath',
            'runtime_path': 'runtimePath'
        }

        self._database_name = database_name
        self._memory_target_in_mb = memory_target_in_mb
        self._oracle_home_path = oracle_home_path
        self._runtime_path = runtime_path

    @property
    def database_name(self):
        """
        Gets the database_name of this OracleConfig.

        :return: The database_name of this OracleConfig.
        :rtype: str
        """
        return self._database_name

    @database_name.setter
    def database_name(self, database_name):
        """
        Sets the database_name of this OracleConfig.

        :param database_name: The database_name of this OracleConfig.
        :type: str
        """

        self._database_name = database_name

    @property
    def memory_target_in_mb(self):
        """
        Gets the memory_target_in_mb of this OracleConfig.

        :return: The memory_target_in_mb of this OracleConfig.
        :rtype: int
        """
        return self._memory_target_in_mb

    @memory_target_in_mb.setter
    def memory_target_in_mb(self, memory_target_in_mb):
        """
        Sets the memory_target_in_mb of this OracleConfig.

        :param memory_target_in_mb: The memory_target_in_mb of this OracleConfig.
        :type: int
        """

        self._memory_target_in_mb = memory_target_in_mb

    @property
    def oracle_home_path(self):
        """
        Gets the oracle_home_path of this OracleConfig.

        :return: The oracle_home_path of this OracleConfig.
        :rtype: str
        """
        return self._oracle_home_path

    @oracle_home_path.setter
    def oracle_home_path(self, oracle_home_path):
        """
        Sets the oracle_home_path of this OracleConfig.

        :param oracle_home_path: The oracle_home_path of this OracleConfig.
        :type: str
        """

        self._oracle_home_path = oracle_home_path

    @property
    def runtime_path(self):
        """
        Gets the runtime_path of this OracleConfig.

        :return: The runtime_path of this OracleConfig.
        :rtype: str
        """
        return self._runtime_path

    @runtime_path.setter
    def runtime_path(self, runtime_path):
        """
        Sets the runtime_path of this OracleConfig.

        :param runtime_path: The runtime_path of this OracleConfig.
        :type: str
        """

        self._runtime_path = runtime_path

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OracleConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
