# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ShareLocation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, appliance_details=None, path=None, type=None):
        """
        ShareLocation - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'appliance_details': 'ApplianceDetails',
            'path': 'str',
            'type': 'str'
        }

        self.attribute_map = {
            'appliance_details': 'applianceDetails',
            'path': 'path',
            'type': 'type'
        }

        self._appliance_details = appliance_details
        self._path = path
        self._type = type

    @property
    def appliance_details(self):
        """
        Gets the appliance_details of this ShareLocation.

        :return: The appliance_details of this ShareLocation.
        :rtype: ApplianceDetails
        """
        return self._appliance_details

    @appliance_details.setter
    def appliance_details(self, appliance_details):
        """
        Sets the appliance_details of this ShareLocation.

        :param appliance_details: The appliance_details of this ShareLocation.
        :type: ApplianceDetails
        """

        self._appliance_details = appliance_details

    @property
    def path(self):
        """
        Gets the path of this ShareLocation.
        Exported share path

        :return: The path of this ShareLocation.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this ShareLocation.
        Exported share path

        :param path: The path of this ShareLocation.
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")

        self._path = path

    @property
    def type(self):
        """
        Gets the type of this ShareLocation.
        Exported share type, e.g. NFS

        :return: The type of this ShareLocation.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ShareLocation.
        Exported share type, e.g. NFS

        :param type: The type of this ShareLocation.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ShareLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
