# coding: utf-8

"""
    Velocity-Sandbox

    API to create a Velocity Sandbox

    OpenAPI spec version: 1.0.0
    Contact: alay.vakil@veritas.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class CreateSandboxApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def create_sandbox(self, velocity_token, body, **kwargs):
        """
        
        Create Velocity Template , PointinTime and  Sandbox
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.create_sandbox(velocity_token, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str velocity_token: Token received from Velocity Oauth API call (required)
        :param ComposedObject body: ComposedObject (required)
        :return: Sandbox
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.create_sandbox_with_http_info(velocity_token, body, **kwargs)
        else:
            (data) = self.create_sandbox_with_http_info(velocity_token, body, **kwargs)
            return data

    def create_sandbox_with_http_info(self, velocity_token, body, **kwargs):
        """
        
        Create Velocity Template , PointinTime and  Sandbox
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.create_sandbox_with_http_info(velocity_token, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str velocity_token: Token received from Velocity Oauth API call (required)
        :param ComposedObject body: ComposedObject (required)
        :return: Sandbox
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['velocity_token', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_sandbox" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'velocity_token' is set
        if ('velocity_token' not in params) or (params['velocity_token'] is None):
            raise ValueError("Missing the required parameter `velocity_token` when calling `create_sandbox`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_sandbox`")


        collection_formats = {}

        resource_path = '/oraclesandbox'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}
        if 'velocity_token' in params:
            header_params['velocity_token'] = params['velocity_token']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['Bearer']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Sandbox',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
